language: php

# Behat no longer passes when false.
sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.3

env:
  global:
    - IGNORE_PATHS=ignore
    - IGNORE_NAMES=ignore_name.php
    - MUSTACHE_IGNORE_NAMES=broken.mustache
    - DB=pgsql
    - MOODLE_BRANCH=master
    - PROFILE=chrome

install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - make init

  # Mimic how a Moodle plugin would be run.
  - cp -R tests/Fixture/moodle-local_travis ../moodle-local_travis
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_travis; pwd)

  # Finally, the standard install step.
  - moodle-plugin-ci add-plugin moodleou/moodle-editor_ousupsub
  - moodle-plugin-ci add-plugin moodleou/moodle-qtype_pmatch
  - moodle-plugin-ci install

script:
  - make test-phpunit

  # This is basically "integration" testing.

  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat --profile $PROFILE