language: php

addons:
  postgresql: "9.4"

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1

env:
  global:
    - IGNORE_PATHS=ignore
    - IGNORE_NAMES=ignore_name.php
    - MUSTACHE_IGNORE_NAMES=broken.mustache
    - DB=pgsql
    - MOODLE_BRANCH=MOODLE_36_STABLE
    - PROFILE=chrome

install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - make init
  # Start Selenium Standalone with Chrome/Firefox installed.
  - docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-${PROFILE}:3
  # Mimic how a Moodle plugin would be run.
  - cp -R tests/Fixture/moodle-local_travis ../moodle-local_travis
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_travis; pwd)

  # Finally, the standard install step.
  - moodle-plugin-ci add-plugin moodleou/moodle-editor_ousupsub
  - moodle-plugin-ci add-plugin moodleou/moodle-qtype_pmatch
  - moodle-plugin-ci install

script:
  # This is basically "integration" testing.
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --profile $PROFILE